[[main]]
  identifier = "Documentation"
  name = "Documentation"
  url = "docs"
  weight = 1

[[main]]
  identifier = "Blog"
  name = "Blog"
  url = "blog"
  weight = 3

[[main]]
  identifier = "Community"
  name = "Community"
  url = "blog"
  weight = 3


[[main]]
  identifier = "Contact"
  name = "Contact"
  url = "contact"
  weight = 4