[[main]]
  identifier = "Docs"
  name = "Tài liệu"
  url = "docs"
  weight = 1

[[main]]
  identifier = "Blog"
  name = "Blog"
  url = "blog"
  weight = 3

[[main]]
  identifier = "Contact"
  name = "Liên hệ"
  url = "contact"
  weight = 4